spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAPS}
    consumer:
      group-id: matching-group
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 3
        max.in.flight.requests.per.connection: 1
    listener:
      ack-mode: manual
      missing-topics-fatal: false
  retry:
    interval: 1000
    max-attempts: 3